# Generated by Django 5.0.1 on 2024-02-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_current_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_semester',
        ),
    ]
