# Generated by Django 5.0.1 on 2024-02-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.FloatField(blank=True, default=100.0, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('default_name', models.CharField(max_length=100)),
                ('lock_weights', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('desired_score', models.FloatField(default=100.0)),
                ('units', models.IntegerField(verbose_name='Units/Credits')),
                ('display_color', models.CharField(default='#FFFFFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=7)),
                ('year', models.IntegerField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grademaster.assignmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='assignmenttype',
            name='associated_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_types', to='grademaster.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='grademaster.semester'),
        ),
    ]
