# Generated by Django 5.0.1 on 2024-02-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grademaster', '0003_assignment_user_assignmenttype_user_class_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
